version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.17
  pre_build:
    commands:
      - echo Build started
      - go test
  build:
    commands:
      - go build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - photo-lambda
  name: photo-lambda-$(date +%Y%m%d.%H%M%s).zip
