version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18
  pre_build:
    commands:
      - echo Build started
      - go mod download github.com/aws/aws-lambda-go
      - go get github.com/TheBellman/photo-lambda
      - go test
  build:
    commands:
      - go mod download github.com/aws/aws-lambda-go
      - go get github.com/TheBellman/photo-lambda
      - go build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - photo-lambda
  name: photo-lambda-$(date +%Y%m%d.%H%M%s).zip
