version: 0.2

env:
  image: aws/codebuild/amazonlinux2-x86_64-standard:4.0

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo Build started
      - go test
  build:
    commands:
      - go build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - photo-lambda
  name: photo-lambda-$(date +%Y%m%d.%H%M%s).zip
